# Generated by Django 4.1.7 on 2023-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestotelMap', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='libelle',
            field=models.CharField(max_length=100, unique=True, verbose_name='Libellé'),
        ),
    ]
