# Generated by Django 4.1.7 on 2023-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestotelMap', '0004_alter_categorie_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='localisation',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ville'),
        ),
    ]
