# Generated by Django 4.1.7 on 2023-11-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestotelMap', '0006_rename_categorie_etablissement_id_catego_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='id_catego',
            new_name='catego',
        ),
        migrations.RenameField(
            model_name='etablissement',
            old_name='id_local',
            new_name='local',
        ),
    ]
