# Generated by Django 4.1.7 on 2023-11-11 23:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestotelMap', '0007_rename_id_catego_etablissement_catego_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
            ],
            options={
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Etab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Téléphone')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
                ('catego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.catego', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name_plural': 'Etablissement',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Ville')),
                ('commune', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Commune')),
                ('quartier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
            ],
            options={
                'verbose_name_plural': 'Localisation',
            },
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='catego',
        ),
        migrations.RemoveField(
            model_name='etablissement',
            name='local',
        ),
        migrations.DeleteModel(
            name='Localisation',
        ),
        migrations.AddField(
            model_name='etab',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.local', verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='appartenir',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.catego', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='appartenir',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestotelMap.etab', verbose_name='Etablissement'),
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='Etablissement',
        ),
    ]
