# Generated by Django 4.1.7 on 2023-11-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestotelMap', '0008_catego_etab_local_remove_etablissement_catego_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appartenir',
        ),
    ]
